### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by nyudenkov** [shihabmridha/educative.io-downloader#20]
(node:72254) UnhandledPromiseRejectionWarning: Error: Page crashed!
    at Page._onTargetCrashed (/home/user/work/other/educative.io-downloader/node_modules/puppeteer/lib/Page.js:216:24)
    at CDPSession.<anonymous> (/home/user/work/other/educative.io-downloader/node_modules/puppeteer/lib/Page.js:124:56)
    at CDPSession.emit (events.js:315:20)
    at CDPSession._onMessage (/home/user/work/other/educative.io-downloader/node_modules/puppeteer/lib/Connection.js:200:12)
    at Connection._onMessage (/home/user/work/other/educative.io-downloader/node_modules/puppeteer/lib/Connection.js:112:17)
    at WebSocket.<anonymous> (/home/user/work/other/educative.io-downloader/node_modules/puppeteer/lib/WebSocketTransport.js:44:24)
    at WebSocket.onMessage (/home/user/work/other/educative.io-downloader/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/home/user/work/other/educative.io-downloader/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:315:20)
(node:72254) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)

Why can I get this error?

**Comment by devKshitijJain** [comment]
@shihabmridha any idea on this?

**Comment by nyudenkov** [comment]
Resolved by increasing `HTTP_REQUEST_TIMEOUT` const in globals and adding `'--no-sandbox', '--disable-dev-shm-usage'` to args in browser.
