### ISSUE TITLE
Not able to install dependencies. Error while installing dependency "puppeteer"

### ISSUE THREAD

**Issue by yashikabhoge** [shihabmridha/educative.io-downloader#43]
I am getting below error when I execute "npm install" command to install dependencies,

> npm install

> puppeteer@2.0.0 install C:\amit_fegade\softwares\educative-io\educative.io-downloader-master\node_modules\puppeteer
> node install.js

ERROR: Failed to download Chromium r706915! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1473:34)
    at TLSSocket.emit (events.js:311:20)
    at TLSSocket._finishInit (_tls_wrap.js:916:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:686:12)
  -- ASYNC --
    at BrowserFetcher.<anonymous> (C:\amit_fegade\softwares\educative-io\educative.io-downloader-master\node_modules\puppeteer\lib\helper.js:111:15)
    at Object.<anonymous> (C:\amit_fegade\softwares\educative-io\educative.io-downloader-master\node_modules\puppeteer\install.js:62:16)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'SELF_SIGNED_CERT_IN_CHAIN'
}
npm WARN rollback Rolling back debug@3.2.6 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\amit_fegade\softwares\educative-io\educative.io-downloader-master\node_modules\https-proxy-agent\node_modules'
npm WARN educative.io-downloader@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@2.0.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@2.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\amitf\AppData\Roaming\npm-cache\_logs\2020-05-23T17_24_29_780Z-debug.log.

**Comment by shihabmridha** [comment]
This issue is related to Puppeteer not our script.
